name: tbqc
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python=3.13

 
  # Phase 1 – QC & preprocessing
  - fastqc=0.12.1
  - trimmomatic=0.39
  - multiqc
  - seqtk

  # Phase 2 – Alignment & taxonomy-related tools
  - bwa
  - samtools
  - bcftools
  - tabix  
  
  # Phase 3 – Variant calling
  - freebayes

